# Generated by Django 2.1.7 on 2019-03-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('released_on', models.DateField()),
                ('genre', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
            ],
        ),
    ]
